### ISSUE TITLE
프레임워크 변경 안건입니다.

### ISSUE THREAD

**Issue by yeanajun** [yeanajun/My.CL#11]
추천 알고리즘도 파이썬으로 진행하기도 하고 node.js , react.js 연결 문제 때문에 혹시 python에 있는 django는 어떠실까요???

**Comment by kim-chae-yeon** [comment]
좋아용!

**Comment by kwakchanhyuk** [comment]
저도 파이썬 기반으로 하는거라서 그렇게 하는게 더 좋을 것 같습니다.

**Comment by yeanajun** [comment]
그럼 필요한 레포지토리를 제외한 나머지 초기화 하겠습니다.
