### ISSUE TITLE
역할분담입니다.

### ISSUE THREAD

**Issue by yeanajun** [yeanajun/My.CL#2]
1. 프론트엔드
2. 백엔드+데이터베이스
3. 크롤링

하고싶은거나 해본것중에 원하는거 있으면 남겨주세요!!

**Comment by yeanajun** [comment]
프론트앤드

**Comment by yeanajun** [comment]
전 프론트엔드 하고 싶습니다!

**Comment by kim-chae-yeon** [comment]
크롤링, 백엔드 경험이 있어 둘 중 상관없습니다! 
백엔드 해야할 부분이 많으니까 다같이 도우면서 하면 좋을거같아요~

**Comment by kwakchanhyuk** [comment]
크롤링 말고도 데이터 분석 부분 코드 짜는 부분도 필요할 것 같아요~

**Comment by kim-chae-yeon** [comment]
그럼

예나: 프론트
찬혁: 데이터 분석
채연: 크롤링
백엔드 부분은 다같이 도우면서로
결정낼게요!
