### ISSUE TITLE
프레임워크

### ISSUE THREAD

**Issue by yeanajun** [yeanajun/My.CL#3]
웹과 관련된 프레임워크 사용해보신거나 해보고싶은거 남겨주세요!

**Comment by kim-chae-yeon** [comment]
파이썬 기반 django 경험 있습니다!
평소 node.js에도 관심이 있어 node.js도 좋을거같아요~

**Comment by kwakchanhyuk** [comment]
node.js 사용하고 DBMS는 FireBase를 쓰는게 어떨까요?
