### ISSUE TITLE
강의 추천을 위한 데이터 수집

### ISSUE THREAD

**Issue by kim-chae-yeon** [yeanajun/My.CL#4]
기존 계획으로 여러 인터넷 강의 사이트에 강의 후기를 모두 크롤링하여 
형태소 분석으로 필기 많음, 진도 빠름 등 카테고리 분류를 하려했으나 구현 상으로 힘들거 같습니다.
 -> 필기 많다는 내용 등 후기에 보이지 않는 내용들이 있습니다.
 -> 후기를 크롤링하는 과정에서 클릭해야 각 후기를 볼 수 있고, 링크 query로도 접근이 힘들어 일일히 수집해야하는 번거로움이 있습니다.

그래서, 데이터 수집하는 다른 방법을 생각해봤습니다.
 -> 여러 사이트의 강의 목록을 크롤링해와서 우리 서비스 웹에 태그를 이용할 수 있는 후기란을 생성합니다.
 -> 그것을 통해 데이터 분석 및 분류를 하여 추천 서비스를 제공합니다.
 -> 이 방법을 사용하면 '진도 빠름', '필기 많음'으로 검색할 수 있다는 또다른 차별성이 생깁니다.

이 외의 다른 방법이 있다면 공유하고 더 나은 방법으로 진행해봤으면 좋겠습니다!

**Comment by kwakchanhyuk** [comment]
크롤링 과정과 머신러닝 부분이 생각보다 더 간단하게 구현이 될 것 같네요.
추천 알고리즘 부분 정리해서 알려드리도록 하겠습니다.

**Comment by yeanajun** [comment]
좋은 의견 같습니다!
해당 의견에 추가해 사용자가 후기를 남길때 태그와 코멘트도 같이 남긴 후 태그를 통해 추천 강의를 제공하고 추천 강의와 함께 코멘트도 사용자에게 같이 보여주면 더욱 더 편리하고 직관적인 서비스가 될 것 같습니다
