### ISSUE TITLE
강의 목록 json 구조 수정 파일에 대한 문제점

### ISSUE THREAD

**Issue by kim-chae-yeon** [yeanajun/My.CL#7]
sample.json과 update_json.py 파일을 읽고 문제점이 보여 이슈 작성합니다.

sample.json파일처럼 json구조가 형성이 되면 firebase에서 데이터를 가져올 때 시간이 엄청 오래 걸리는 현상이 생기고
효율성이 굉장히 떨어 질 것 같습니다. 코드에 대한 수정이 필요할 것 같습니다...

**Comment by kwakchanhyuk** [comment]
여러분들이 주신 의견을 보고 저도 여러가지 찾아보면서 알아본 결과 제가 만들어 놓은 sample.json파일 형태를 데이터 베이스에 집어 넣는 방식은 무리가 있다고 판단하였습니다.  물론 upadte_json.py파일도 사용할 필요가 없어지겠지요... 
앞서 말씀하신 것처럼 기존에 크롤링한 jason파일에서 강의 목록만 뽑아 와서 새로운 데이터베이스를 만들어 관리하는 것은 굉장히 좋은 생각인 것 같습니다.  그러면 mongoDB를 사용해서 두 개의 데이터 프레임을 만들어서 사용하는 방식으로 다시 짜 보도록 하겠습니다.
