### ISSUE TITLE
DB관련 수정사항

### ISSUE THREAD

**Issue by kwakchanhyuk** [yeanajun/My.CL#8]
태그 데이터 부분의 필드 값을 하나 추가해서 기존 크롤링 데이터의 id값을 저장할 부분을 만드는게 좋을 것 같습니다.

**Comment by yeanajun** [comment]
넵 !! 그렇게 해서 진행하는것이 저도 좋다고 생각합니다!

**Comment by kim-chae-yeon** [comment]
태그 데이터의 id값에 강의 목록 id값을 가져와서 설정했습니다!
tag폴더에 tag_create.py 코드를 참고해주시기 바랍니다!
