### ISSUE TITLE
추천 알고리즘 상의 문제점

### ISSUE THREAD

**Issue by kwakchanhyuk** [yeanajun/My.CL#9]
태그 간의 우선순위 문제로 추천 프로그램을 짜는데 어려움을 겪고 있습니다. 이 문제에 대해 같이 논의를 해보면 좋을 것 같습니다.
ex)진도, 잡담, 필기인 세개의 태그가 존재하고 1~10번까지 매겨있는 강의 10개가 있다고 할 때 
     태그 중 사용자가 선택한 가장 높은 것  3개만 추출한다고 할 때

     진도        low            medium         **_high_**      진도가 high 인 것      -> 1, 2, 3 
     잡담        low       **_medium_**         high           잡담이 medium인 것 -> 4, 5, 6
     필기   **_low_**        medium             high           필기가 low인 것         -> 7, 8, 9

     인 경우 진도가 high이고 잡담이 medium이며 필기가 low인 것을 선택하게 되면 어떤 것을 추천해 줘야 될지
     판단하기 힘들어 의견이 있으시면 말씀해 주시면 좋을 것 같습니다.

**Comment by kwakchanhyuk** [comment]
생각해 본건 총 세 개가 있는데
1. 임의로 우선순위 부여
    -> 일반적으로 보통보다 적음이나 많음이 우선순위가 높은 경우가 많기 때문에 보통은 1을 적음 or 많음은 2의 가중치를 부여 
         하여 우선순위를 매기는 방식
2. 사용자의 질의를 통한 우선순위 부여
   -> 가장 중요하다고 생각하는 카테고리 세 가지중 하나를 고르라 해서 그것의 가중치를 2 나머지를 1을 주고 우선순위를 매기 
        는 방식
3. 태그마다 추천 강의 출력
   -> 카테고리 별로 출력을 각각 해주는 방식

또 다른 괜찮은 의견이 있으시면 말씀해 주시면 감사하겠습니다.

**Comment by yeanajun** [comment]
1번 -> 적당히가 1, 많음이 3, 적음이 2 와 같은 가중치를 부여하는 것은 어떨까요? 보통 많은게 가장 원하는것이기 때문에 심리적인 부분에서 저런식으로 가중치를 부여하는 것도 괜찮다고 생각합니다
2번 , 3번 -> 가중치를 부여하는 방법을 제외하고 생각한다면 2번 방법이 가장 효과적일 것이라고 생각합니다.

**Comment by kim-chae-yeon** [comment]
보통을 1의 가중치로 두는 것은 좋은 것 같습니다. 
하지만 잡담같은 경우는 아예 없다시피 하는 것을 우선적으로 원하는 사람을 생각하면 적음의 카테고리 가중치도 무시할 수 없다고 생각합니다.

그러므로 보통을 1의 가중치로 두고, 많음과 적음을 2의 가중치로 두되, 2번 의견과 같이 사용자가 선택한 우선순위에 3을 두는 것도 괜찮다고 생각합니다!

**Comment by kwakchanhyuk** [comment]
여러가지 의견들을 반영한 결과 가중치를 숫자 보다 순서로 부여하는 개념으로 접근해서 총 개수에서 특정 비율로 줄여나가는 방식을 사용해서 알고리즘을 구현하게 되었습니다.
